# Generated by Django 5.2.1 on 2025-05-19 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffee_Co', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeetype',
            options={'verbose_name': 'Coffee Type'},
        ),
        migrations.CreateModel(
            name='CoffeeRecipeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('coffeeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coffee_Co.coffeetype')),
            ],
            options={
                'verbose_name_plural': 'Coffee Recipe Entries',
            },
        ),
    ]
