# Generated by Django 5.2.1 on 2025-05-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffee_Co', '0002_alter_coffeetype_options_coffeerecipeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeerecipeentry',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
            preserve_default=False,
        ),
    ]
