# Generated by Django 5.2.1 on 2025-05-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffee_Co', '0003_coffeerecipeentry_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeerecipeentry',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
